-- MySQL Script generated by MySQL Workbench
-- 04/13/21 17:03:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema certificados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema certificados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `certificados` DEFAULT CHARACTER SET utf8 ;
USE `certificados` ;

-- -----------------------------------------------------
-- Table `certificados`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`estados` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificados`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `connection` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `queue` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `payload` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `exception` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `last_name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `telephone` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cedula` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `adress` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `certificados`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`libros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `createdby_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `modifiedby_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `createdby_id` (`createdby_id` ASC),
  INDEX `modifiedby_id` (`modifiedby_id` ASC),
  CONSTRAINT `libros_ibfk_1`
    FOREIGN KEY (`createdby_id`)
    REFERENCES `certificados`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `libros_ibfk_2`
    FOREIGN KEY (`modifiedby_id`)
    REFERENCES `certificados`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificados`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `certificados`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`permissions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `guard_name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `permissions_name_guard_name_unique` (`name` ASC, `guard_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`model_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`model_has_permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `model_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `model_id`, `model_type`),
  INDEX `model_has_permissions_model_id_model_type_index` (`model_id` ASC, `model_type` ASC),
  CONSTRAINT `model_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `certificados`.`permissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `guard_name` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_guard_name_unique` (`name` ASC, `guard_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`model_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`model_has_roles` (
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `model_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `model_id`, `model_type`),
  INDEX `model_has_roles_model_id_model_type_index` (`model_id` ASC, `model_type` ASC),
  CONSTRAINT `model_has_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `certificados`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`password_resets` (
  `email` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`registros` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_cedula` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombre_empleado` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellidos_empleado` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cargo` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_retiro` DATE NULL DEFAULT NULL,
  `dias_laborados` INT(11) NULL DEFAULT NULL,
  `sueldo` INT(11) NULL DEFAULT NULL,
  `devengado` INT(11) NULL DEFAULT NULL,
  `ley100` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `createdby_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `modifiedby_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `libro_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `registros_createdby_id_foreign` (`createdby_id` ASC),
  INDEX `registros_modifiedby_id_foreign` (`modifiedby_id` ASC),
  INDEX `hola_idx` (`libro_id` ASC),
  CONSTRAINT `hola`
    FOREIGN KEY (`libro_id`)
    REFERENCES `certificados`.`libros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `registros_createdby_id_foreign`
    FOREIGN KEY (`createdby_id`)
    REFERENCES `certificados`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `registros_modifiedby_id_foreign`
    FOREIGN KEY (`modifiedby_id`)
    REFERENCES `certificados`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `certificados`.`role_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`role_has_permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `role_has_permissions_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `role_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `certificados`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_has_permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `certificados`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificados`.`solicituds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificados`.`solicituds` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `modifiedby_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `estado_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `modifiedby_id` (`modifiedby_id` ASC),
  INDEX `solicituds_ibfk_3` (`estado_id` ASC),
  CONSTRAINT `solicituds_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `certificados`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `solicituds_ibfk_2`
    FOREIGN KEY (`modifiedby_id`)
    REFERENCES `certificados`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `solicituds_ibfk_3`
    FOREIGN KEY (`estado_id`)
    REFERENCES `certificados`.`estados` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
